Update node to patch a CVE.
allenai/scholarphi pull request #157
Opened 2020-11-24 05:02 UTC by codeviking

NodeJS distributed a patch for a high severity CVE, see:
https://twitter.com/nodejs/status/1328723765157617672?s=21

I chose to bump the `node` version to `14` from `12` here because
`14` is the latest LTS release, so it seemed like a good thing
to do. Everything appeared to work, though admittedly my
testing only went as far as:

```
cd api/
docker run --rm -it 3000:3000 $(docker build -q .)
curl http://localhost:3000/health

cd ../ui
docker run --rm -it 4000:4000 $(docker build -q .)
open http://localhost:4000/?file=https://arxiv.org/pdf/0801.4750.pdf
```

Everything appeared to work. If more thorough testing is warranged
let me know (and ideally point me at instructions for doing so).

Here's the relevant ticket:
https://github.com/allenai/reviz/issues/155

2020-11-25 01:25 UTC, andrewhead commented
Thank you @codeviking !

2020-11-30 18:15 UTC, mjlangan requested changes
Given we're weeks from wanting to launch this thing to a small audience, I'd feel better about moving to 12.19.1 instead of also upgrading two major versions.

2020-11-30 19:06 UTC, codeviking commented
> Given we're weeks from wanting to launch this thing to a small audience, I'd feel better about moving to 12.19.1 instead of also upgrading two major versions.

Sure. I changed the version from `14.*` to `12.20`, the latest `12.*` release.

It's very easy to rollback if something goes wrong (we'd just revert this commit).  Please TAL and let me know if it's ok to merge now!

2020-11-30 20:10 UTC, mjlangan approved these changes
👍

2020-11-30 20:27 UTC, merged